name: AbsolutEvents
version: ${project.version}
description: Plugin de eventos do servidor.

author: _Saynt
website: ${project.url}

main: com.absolutgg.absolutevents.AbsolutEventsPlugin
api-version: '1.21'

softdepend:
  - SimpleClans
  - Vault
  - PlaceholderAPI
  - WorldEdit
  - FastAsyncWorldEdit
  - MMOItems
  - ItemsAdder

commands:
  evento:
    description: Sistema de eventos do servidor
    usage: /evento
    aliases:
      - eventos
      - evento
      - events
      - event
      - ev
    permission: absolutevents.use
    permission-message: "§cSem permissão."